####Create a sample code of partitioning. Use 5 as k argumemnt.

In [1]:
import numpy as np

rng = np.random.RandomState(0)
x = rng.randint(10, size=(10, 10))

In [2]:
x

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [3]:
#y-axis Partitioning
print("Y-axis:\n\n",np.partition(x,5,axis=0)) 
#x-axis Partitioning
print("X-axis:\n\n",np.partition(x,5,axis=1))          

Y-axis:

 [[0 0 1 1 1 3 0 1 0 1]
 [5 1 0 0 3 0 1 2 2 0]
 [4 3 3 3 3 3 2 3 0 0]
 [2 3 3 4 4 3 3 5 2 1]
 [0 4 5 4 4 4 3 4 4 1]
 [5 4 5 5 5 6 3 5 4 2]
 [8 6 8 7 6 7 4 6 4 2]
 [7 9 8 9 7 8 7 7 5 3]
 [5 9 8 8 9 9 5 7 7 9]
 [9 9 8 9 7 9 6 7 8 4]]
X-axis:

 [[0 2 3 3 3 4 5 5 9 7]
 [1 1 7 6 6 7 7 8 8 8]
 [3 0 3 0 4 5 5 8 9 9]
 [1 1 0 2 3 3 3 7 8 3]
 [2 0 0 2 3 4 7 7 9 9]
 [0 1 4 4 4 5 5 6 8 9]
 [1 3 1 2 6 7 7 8 9 9]
 [3 0 3 4 4 4 4 5 6 9]
 [0 1 3 4 4 4 7 5 8 5]
 [0 0 1 2 2 3 4 5 9 5]]


####Create a sample structure array using following specification:
####name: OrderDate, format: unicode maximum 8 characters
####name: OrderAmount, format: float 8-bytes
####name: OrderNumber, format: integer 4-bytes
####name: OrderName, format: unicode maximum 20 characters

In [5]:
data = np.dtype({'names':('OrderDate', 'OrderAmount', 'OrderNumber','OrderName'),
                          'formats':('U8', 'f8', 'i4','U20')})

In [6]:
data

dtype([('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')])

####3. Using 2, create a NumPy array of 10 elements with proper initialization of the structured array. Note order numbers must be between 101 - 110.

In [7]:
OrderDate=['04062023','04072023','04082023','04092023','04102023','04112023','04122023','04132023','04142023','04152023']
OrderAmount=[50.00,100.00,150.00,200.00,250.00,300.00,350.00,400.00,450.00,500.00]
OrderNumber=[101,102,103,104,105,106,107,108,109,110]
OrderName=['Any', 'Many', 'Alia', 'Kaela','Mili','Ant','Gem','Fire','Hope','Faith']

data = np.zeros(10,dtype={'names':('OrderDate', 'OrderAmount', 'OrderNumber','OrderName'),'formats':('U8', 'f8', 'i4','U20')}) 

# Value assignments to the structured array
data['OrderDate'] = OrderDate
data['OrderAmount'] = OrderAmount
data['OrderNumber'] = OrderNumber
data['OrderName'] = OrderName

print(data)

[('04062023',  50., 101, 'Any') ('04072023', 100., 102, 'Many')
 ('04082023', 150., 103, 'Alia') ('04092023', 200., 104, 'Kaela')
 ('04102023', 250., 105, 'Mili') ('04112023', 300., 106, 'Ant')
 ('04122023', 350., 107, 'Gem') ('04132023', 400., 108, 'Fire')
 ('04142023', 450., 109, 'Hope') ('04152023', 500., 110, 'Faith')]


#### 4. Using the array in #3, filter the array to return orders with order number less than 105.

In [8]:
print(data[data['OrderNumber']<105])

[('04062023',  50., 101, 'Any') ('04072023', 100., 102, 'Many')
 ('04082023', 150., 103, 'Alia') ('04092023', 200., 104, 'Kaela')]


####5. Using the code snippet below, fill-in the cell to generate the array as shown at the bottom.
You will need to use fancy indexing and masking. <br>
Select rows with indices 0, 3, 4, 6, 7<br>
Use column masking to return every other columns. The first column will be returned, 2nd column will not and so on.<br>

In [10]:
# Selecting rows with indices 0, 3, 4, 6, 7
rows = [0, 3, 4, 6, 7]
selected_rows = x[rows]

# Using column masking to return every other columns
columns = np.arange(0, x.shape[1], 2)
selected_columns = selected_rows[:, columns]

print(selected_columns)

[[5 3 7 3 2]
 [2 8 3 3 0]
 [9 0 7 2 2]
 [8 1 9 3 7]
 [0 5 4 6 4]]
